# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'SocketIOSandbox' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SocketIOSandbox
  pod "Socket.IO-Client-Swift", "~> 15.2.0"

  target 'SocketIOSandboxTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
